# Generated by Django 3.1.3 on 2021-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COUNTRY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('para1', models.CharField(blank=True, max_length=600)),
                ('para2', models.CharField(blank=True, max_length=600)),
            ],
        ),
    ]
